More changes to support raspberry pi

diff --git a/exact_dot_dotfiles/misc/run_once_thefuck.zsh.tmpl b/exact_dot_dotfiles/misc/run_once_thefuck.zsh.tmpl
--- a/exact_dot_dotfiles/misc/run_once_thefuck.zsh.tmpl
+++ b/exact_dot_dotfiles/misc/run_once_thefuck.zsh.tmpl
@@ -1,10 +1,18 @@
-#!/usr/bin/env zsh 
+#!/usr/bin/env zsh
+
+{{- if .minimalinstall }}
+exit 0
+{{- end }}
 
 source ~/.local/share/chezmoi/.helpers
 
 if is_installed fuck; then
   success 'thefuck is already installed'
 else
+  if ! is_installed pip3; then
+    warn 'pip required to install thefuck'
+    exit 1
+  fi
   started Installing thefuck
   {{- if eq .chezmoi.os "linux" }}
   successfully sudo pip3 install thefuck
